// Short (and, for the Premium tier, extended) video clips for AI design
// concepts, via Google's Veo (same account/key as lib/gemini.ts's image
// generation). Verified directly against the real API before wiring in:
// model id confirmed via ListModels rather than guessed (a prior wrong
// guess 404'd), and the extension-chaining approach for durations beyond a
// single generation's 8-second cap was verified end-to-end too (8s clip ->
// one extension call -> confirmed 15s output via ffprobe).
//
// The image field's shape ({bytesBase64Encoded, mimeType}, flat -- NOT
// nested under inlineData) is the Vertex AI convention, which is unusual
// since this app otherwise calls the Gemini Developer API everywhere else
// -- but it's what this specific model actually accepts. Confirmed by
// directly curling generativelanguage.googleapis.com with real API calls
// (not docs, which disagreed and sent me down the wrong path once): a
// switch to {inlineData: {mimeType, data}} gets rejected outright with
// "`inlineData` isn't supported by this model", while this flat shape
// completes successfully end-to-end -- retested with a throwaway 1x1 image,
// a realistic ~1MB RGB photo, and an RGBA (alpha channel) photo, all three
// polled to a real downloadable video.uri. Don't "fix" this again without
// re-verifying against the live API first.
//
// Video generation is async: submit a job (predictLongRunning), poll the
// returned operation until done. A single generation maxes out around 8
// seconds; going longer means feeding the previous result's video object
// back in as the "video" field alongside a new prompt, which each add
// ~7 more seconds to a single merged output file.

const MODEL = "veo-3.1-fast-generate-preview";
const START_URL = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:predictLongRunning`;
const SECONDS_PER_EXTENSION = 7;
const INITIAL_CLIP_SECONDS = 8;
const MAX_ATTEMPTS = 3;

type VeoVideoRef = { uri: string };

async function submitAndPollOnce(apiKey: string, instance: Record<string, unknown>): Promise<VeoVideoRef> {
  const startRes = await fetch(START_URL, {
    method: "POST",
    headers: { "x-goog-api-key": apiKey, "Content-Type": "application/json" },
    body: JSON.stringify({ instances: [instance] }),
  });
  if (!startRes.ok) {
    const text = await startRes.text();
    throw new Error(`Veo start error ${startRes.status}: ${text}`);
  }
  const { name: operationName } = await startRes.json();
  if (!operationName) {
    throw new Error("Veo did not return an operation name");
  }

  const maxAttempts = 40; // up to ~3.5 minutes per hop — video generation isn't instant
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    await new Promise((r) => setTimeout(r, 5000));
    const pollRes = await fetch(`https://generativelanguage.googleapis.com/v1beta/${operationName}`, {
      headers: { "x-goog-api-key": apiKey },
    });
    if (!pollRes.ok) {
      const text = await pollRes.text();
      throw new Error(`Veo poll error ${pollRes.status}: ${text}`);
    }
    const pollData = await pollRes.json();
    if (pollData.error) {
      throw new Error(`Veo generation failed: ${JSON.stringify(pollData.error)}`);
    }
    if (pollData.done) {
      const video = pollData.response?.generateVideoResponse?.generatedSamples?.[0]?.video;
      if (!video?.uri) {
        throw new Error(`Veo finished but returned no video: ${JSON.stringify(pollData).slice(0, 500)}`);
      }
      return video;
    }
  }
  throw new Error("Veo video generation timed out");
}

// Google's Veo preview API is demonstrably flaky -- confirmed directly while
// debugging a real customer failure: a request using a format already
// proven correct (see file header) failed once with "internal server
// issue... try again in a few minutes", and production has hit a confusing
// 400 ("Input video must be a video that was generated by VEO that has been
// processed") on requests structurally identical to ones that succeeded
// moments later with zero code change. Retry the whole start+poll sequence
// rather than fail an entire paid order over what's very likely a
// transient hiccup on Google's end.
async function submitAndPoll(apiKey: string, instance: Record<string, unknown>): Promise<VeoVideoRef> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    try {
      return await submitAndPollOnce(apiKey, instance);
    } catch (err) {
      lastErr = err;
      console.error(`Veo attempt ${attempt + 1}/${MAX_ATTEMPTS} failed:`, err instanceof Error ? err.message : err);
      if (attempt < MAX_ATTEMPTS - 1) {
        await new Promise((r) => setTimeout(r, 3000 * 2 ** attempt));
      }
    }
  }
  throw lastErr;
}

export async function generateDesignVideo(
  conceptImage: Buffer,
  prompt: string,
  targetDurationSeconds = 8
): Promise<Buffer> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY isn't configured");
  }

  let video = await submitAndPoll(apiKey, {
    prompt: `Slow cinematic pan across this landscaped yard: ${prompt}. Smooth camera movement, photorealistic, no people.`,
    image: { bytesBase64Encoded: conceptImage.toString("base64"), mimeType: "image/png" },
  });

  let currentDuration = INITIAL_CLIP_SECONDS;
  while (currentDuration < targetDurationSeconds) {
    video = await submitAndPoll(apiKey, {
      prompt: "Continue the same slow cinematic pan, revealing more of the yard. Smooth camera movement, photorealistic, no people.",
      video,
    });
    currentDuration += SECONDS_PER_EXTENSION;
  }

  const downloadRes = await fetch(video.uri, { headers: { "x-goog-api-key": apiKey } });
  if (!downloadRes.ok) {
    throw new Error(`Veo video download error ${downloadRes.status}`);
  }
  return Buffer.from(await downloadRes.arrayBuffer());
}
