// One-time seed for the MaterialCatalogItem browsable reference catalog --
// real landscaping materials/plants researched for Austin/Central Texas
// (matching the business's actual service area). Run with:
//   npx tsx scripts/seedMaterialCatalog.ts
// Safe to re-run: upserts on the [category, name] unique constraint.
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ITEMS: { category: string; name: string; description?: string }[] = [
  // Rocks & Stone
  { category: "Rocks & Stone", name: "River Rock", description: "Smooth, rounded stones, 1-4in. Natural edging for beds and drainage areas." },
  { category: "Rocks & Stone", name: "Pea Gravel", description: "Small rounded rock, 1/4-5/8in. Walkways, playgrounds, drainage." },
  { category: "Rocks & Stone", name: "Crushed Granite", description: "Angular crushed stone. Driveways and base material." },
  { category: "Rocks & Stone", name: "Decomposed Granite", description: "Fine weathered granite. Paths, patios, xeriscaping." },
  { category: "Rocks & Stone", name: "Flagstone (Limestone)", description: "Flat natural stone slabs for patios and walkways." },
  { category: "Rocks & Stone", name: "Flagstone (Sandstone)", description: "Flat natural stone slabs, warm tones. Patios and walkways." },
  { category: "Rocks & Stone", name: "Boulders", description: "Large accent stones, 1ft+ diameter. Focal points, retaining features." },
  { category: "Rocks & Stone", name: "Lava Rock", description: "Lightweight porous volcanic rock. Ground cover, fire features." },
  { category: "Rocks & Stone", name: "Cobblestone", description: "Rounded paving stones. Borders, driveways, accents." },
  { category: "Rocks & Stone", name: "Drainage Gravel", description: "Coarse gravel for French drains and drainage beds." },
  { category: "Rocks & Stone", name: "Slate", description: "Flat, layered natural stone. Walkways and accents, gray/blue tones." },
  { category: "Rocks & Stone", name: "Bluestone", description: "Dense blue-gray flagstone. Premium patios and steps." },
  { category: "Rocks & Stone", name: "Rip Rap", description: "Large angular stones, 6-24in. Erosion control on slopes and drainage." },
  { category: "Rocks & Stone", name: "Crushed Limestone", description: "Common Central Texas base rock, white to gray. Driveways and road base." },
  { category: "Rocks & Stone", name: "Limestone Road Base", description: "Compactable limestone fines, standard driveway and path sub-base in this area." },
  { category: "Rocks & Stone", name: "Caliche", description: "Native Central Texas calcium-carbonate base material, common for driveways." },
  { category: "Rocks & Stone", name: "Moss Rock", description: "Native Texas limestone boulders with natural moss/lichen patina, popular accent stone." },

  // Mulch
  { category: "Mulch", name: "Hardwood Mulch", description: "Rich dark color from oak/maple/beech. Slowly acidifies soil." },
  { category: "Mulch", name: "Cedar Mulch", description: "Natural insect-deterrent oils, slow to decompose, fades to gray over time." },
  { category: "Mulch", name: "Pine Bark Mulch", description: "Decomposes faster, needs more frequent refresh." },
  { category: "Mulch", name: "Cypress Mulch", description: "Long-lasting and naturally insect-repellent." },
  { category: "Mulch", name: "Pine Straw", description: "Lightweight dried pine needles, ideal on slopes." },
  { category: "Mulch", name: "Dyed Red Mulch", description: "Recycled wood, tinted for uniform red color." },
  { category: "Mulch", name: "Dyed Black Mulch", description: "Recycled wood, tinted for uniform black color." },
  { category: "Mulch", name: "Dyed Brown Mulch", description: "Recycled wood, tinted for uniform dark brown color." },
  { category: "Mulch", name: "Rubber Mulch", description: "Durable, long-lasting. Playgrounds and pet-friendly areas." },
  { category: "Mulch", name: "Straw Mulch", description: "Lightweight, biodegradable. Garden beds and new lawn seeding." },

  // Soil
  { category: "Soil", name: "Topsoil", description: "General-purpose soil for lawns and beds." },
  { category: "Soil", name: "Garden Soil", description: "Screened topsoil amended with compost, for garden beds." },
  { category: "Soil", name: "Compost", description: "Nutrient-rich organic matter to improve any soil type." },
  { category: "Soil", name: "Sandy Loam", description: "Balanced sand/silt/clay mix with good drainage." },
  { category: "Soil", name: "Raised Bed Soil", description: "Lightweight blend suited for raised garden beds." },
  { category: "Soil", name: "Clay Soil Amendment", description: "Improves drainage and workability of heavy clay soil." },

  // Trees (Austin / Central Texas appropriate)
  { category: "Trees", name: "Live Oak", description: "Sprawling evergreen canopy, drought-tolerant once established." },
  { category: "Trees", name: "Texas Red Oak", description: "Native, brilliant red/orange fall foliage, drought tolerant." },
  { category: "Trees", name: "Monterrey Oak", description: "Fast-growing, drought-tolerant shade tree." },
  { category: "Trees", name: "Cedar Elm", description: "Highly resilient native, reliable shade and wildlife habitat." },
  { category: "Trees", name: "Texas Redbud", description: "10-20ft, pink/purple blooms in March-April." },
  { category: "Trees", name: "Mexican Sycamore", description: "Fast-growing native, large green leaves with silver undersides." },
  { category: "Trees", name: "Crape Myrtle", description: "Summer-blooming ornamental, available in white, pink, red, purple." },
  { category: "Trees", name: "Bald Cypress", description: "Deciduous conifer, tolerates wet or dry soil, feathery foliage." },
  { category: "Trees", name: "Texas Mountain Laurel", description: "Evergreen, fragrant purple spring blooms." },
  { category: "Trees", name: "Desert Willow", description: "Small ornamental tree, orchid-like pink/lavender blooms." },
  { category: "Trees", name: "Chinese Pistache", description: "Excellent fall color, heat and drought tolerant." },
  { category: "Trees", name: "Yaupon Holly", description: "Evergreen, red berries, works as tree or large shrub." },

  // Flowers / plants (Austin / Central Texas appropriate + popular annuals, wide color range)
  { category: "Flowers", name: "Texas Lantana", description: "Yellow, orange, and pink clustered blooms, spring through fall." },
  { category: "Flowers", name: "Purple Coneflower", description: "Purple daisy-like blooms, drought tolerant, attracts pollinators." },
  { category: "Flowers", name: "Autumn Sage", description: "Red, pink, coral, or white blooms, spring until frost." },
  { category: "Flowers", name: "Texas Sage", description: "Compact shrub with pink-lavender blooms." },
  { category: "Flowers", name: "Blackfoot Daisy", description: "Low-growing white daisy-like blooms, very drought resistant." },
  { category: "Flowers", name: "Turk's Cap", description: "Red tubular blooms, spring through fall, hummingbird favorite." },
  { category: "Flowers", name: "Zexmenia", description: "Golden-yellow daisies, blooms May-November." },
  { category: "Flowers", name: "Prairie Verbena", description: "Round clusters of light purple blooms." },
  { category: "Flowers", name: "Esperanza (Yellow Bells)", description: "Bright yellow trumpet blooms, heat tolerant shrub." },
  { category: "Flowers", name: "Marigold", description: "Yellow and orange annual blooms, easy care." },
  { category: "Flowers", name: "Petunia", description: "Annual available in many colors: pink, purple, white, red, and mixes." },
  { category: "Flowers", name: "Zinnia", description: "Annual available in many sizes and colors, from pastel to bright." },
  { category: "Flowers", name: "Black-Eyed Susan", description: "Yellow petals with a dark center, blooms summer into fall." },
  { category: "Flowers", name: "Daylily", description: "Available in many colors and sizes, low maintenance perennial." },

  // Additional flowers/plants requested by the owner from a broader
  // national nursery inventory list (Home Depot / Lowe's), added in full
  // per explicit request even though several aren't ideal for Austin's
  // climate -- included anyway since that's what was asked for.
  { category: "Flowers", name: "Calibrachoa (Million Bells)", description: "Trailing annual, small petunia-like blooms in many colors." },
  { category: "Flowers", name: "Impatiens", description: "Shade-loving annual, available in bright colors and New Guinea/SunPatiens sun varieties." },
  { category: "Flowers", name: "Geranium", description: "Zonal, trailing ivy, and scented-leaf varieties, red/pink/white blooms." },
  { category: "Flowers", name: "Begonia", description: "Wax-leaf, Angel Wing, Dragon Wing, and tuberous types." },
  { category: "Flowers", name: "Vinca (Madagascar Periwinkle)", description: "Heat-tolerant annual, pink/white/purple star-shaped blooms." },
  { category: "Flowers", name: "Verbena", description: "Trailing basket mixes and upright wild types." },
  { category: "Flowers", name: "Coleus", description: "Grown mainly for colorful foliage, light blue flower spikes." },
  { category: "Flowers", name: "Lobelia", description: "Trailing electric blue, white, and violet varieties." },
  { category: "Flowers", name: "Sweet Alyssum", description: "Low carpet of white or purple blooms, fragrant." },
  { category: "Flowers", name: "Pentas (Egyptian Starcluster)", description: "Clustered star-shaped blooms, attracts butterflies." },
  { category: "Flowers", name: "Celosia", description: "Plume, cockscomb, and wheat types, bold reds/oranges/purples." },
  { category: "Flowers", name: "Angelonia (Summer Snapdragon)", description: "Heat-tolerant spikes in purple, pink, and white." },
  { category: "Flowers", name: "Portulaca (Moss Rose)", description: "Drought-tolerant succulent groundcover with bright blooms." },
  { category: "Flowers", name: "Cosmos", description: "Airy annual, pink/white/orange daisy-like blooms." },
  { category: "Flowers", name: "Sunflower", description: "Dwarf potted to giant seed-packet varieties." },
  { category: "Flowers", name: "Fuchsia", description: "Dangling bi-color blooms, shade hanging baskets." },
  { category: "Flowers", name: "Bacopa", description: "Trailing filler with small white or blue flowers." },
  { category: "Flowers", name: "Gomphrena (Globe Amaranth)", description: "Round papery blooms in purple, pink, white; heat tolerant." },
  { category: "Flowers", name: "Ageratum (Flossflower)", description: "Fuzzy blue, pink, or white clustered blooms." },
  { category: "Flowers", name: "Nicotiana (Flowering Tobacco)", description: "Fragrant star-shaped blooms, evening scent." },
  { category: "Flowers", name: "Osteospordum (African Daisy)", description: "Daisy-like blooms in purple, white, orange, pink." },
  { category: "Flowers", name: "Evolvulus (Blue Daze)", description: "Low mounding annual with sky-blue blooms." },
  { category: "Flowers", name: "Helichrysum (Strawflower)", description: "Papery everlasting blooms, bright colors." },
  { category: "Flowers", name: "Scaevola (Fan Flower)", description: "Trailing fan-shaped purple or white blooms." },
  { category: "Flowers", name: "Torenia (Wishbone Flower)", description: "Shade-tolerant, purple/blue/pink two-tone blooms." },
  { category: "Flowers", name: "Gazania (Treasure Flower)", description: "Bright daisy-like blooms, heat and drought tolerant." },
  { category: "Flowers", name: "Heliotrope", description: "Vanilla-scented purple flower clusters." },
  { category: "Flowers", name: "Bidens", description: "Small yellow star-shaped annual blooms." },
  { category: "Flowers", name: "Annual Salvia (Scarlet Sage)", description: "Bright red, purple, or white summer spikes." },
  { category: "Flowers", name: "Euphorbia (Diamond Frost)", description: "Airy white baby's-breath-like clusters, heat tolerant filler." },
  { category: "Flowers", name: "Coreopsis (Tickseed)", description: "Yellow daisy-like perennial blooms, drought tolerant." },
  { category: "Flowers", name: "Lavender", description: "Fragrant purple spikes, English and Spanish varieties." },
  { category: "Flowers", name: "Perennial Salvia (May Night)", description: "Deep purple-blue spikes, long blooming perennial." },
  { category: "Flowers", name: "Dianthus", description: "Carnations, Sweet William, and pinks; red/pink/white blooms." },
  { category: "Flowers", name: "Hosta", description: "Shade-loving foliage plant with tall lily-like flower stalks." },
  { category: "Flowers", name: "Coral Bells (Heuchera)", description: "Colorful foliage perennial with small bell-shaped blooms." },
  { category: "Flowers", name: "Shasta Daisy", description: "Classic white petals with a yellow center, summer bloomer." },
  { category: "Flowers", name: "Bleeding Heart", description: "Arching stems with pink/white heart-shaped blooms, shade perennial." },
  { category: "Flowers", name: "Peony", description: "Large, full blooms in pink, white, and red; spring perennial." },
  { category: "Flowers", name: "Catmint (Nepeta)", description: "Lavender-blue spikes, drought tolerant, attracts pollinators." },
  { category: "Flowers", name: "Russian Sage", description: "Silvery foliage with airy purple-blue spikes, heat tolerant." },
  { category: "Flowers", name: "Yarrow (Achillea)", description: "Flat-topped clusters in yellow, red, or violet; drought tolerant." },
  { category: "Flowers", name: "Blanket Flower (Gaillardia)", description: "Red-and-yellow daisy-like blooms, very heat tolerant." },
  { category: "Flowers", name: "Phlox", description: "Creeping groundcover and tall summer varieties, many colors." },
  { category: "Flowers", name: "Columbine", description: "Delicate spurred blooms in mixed colors, part-shade perennial." },
  { category: "Flowers", name: "Bee Balm (Monarda)", description: "Red or purple shaggy blooms, attracts hummingbirds." },
  { category: "Flowers", name: "Astilbe", description: "Feathery plumes in pink, red, or white; shade perennial." },
  { category: "Flowers", name: "Sedum (Stonecrop)", description: "Succulent foliage with fall blooms, very drought tolerant." },
  { category: "Flowers", name: "Candytuft", description: "Low mounding white spring blooms, evergreen foliage." },
  { category: "Flowers", name: "Foxglove", description: "Tall spikes of bell-shaped blooms, part shade." },
  { category: "Flowers", name: "Delphinium (Larkspur)", description: "Tall blue or white spring spikes." },
  { category: "Flowers", name: "Lupine", description: "Tall colorful spikes, mixed color varieties." },
  { category: "Flowers", name: "Agastache (Hummingbird Mint)", description: "Fragrant spikes in orange, pink, purple; drought tolerant." },
  { category: "Flowers", name: "Asclepias (Butterfly Weed)", description: "Orange or pink clusters, host plant for monarch butterflies." },
  { category: "Flowers", name: "Hardy Geranium (Cranesbill)", description: "Low mounding perennial with pink/purple blooms." },
  { category: "Flowers", name: "Veronica (Speedwell)", description: "Upright blue or purple flower spikes." },
  { category: "Flowers", name: "Penstemon (Beardtongue)", description: "Tubular blooms in red, pink, or purple; drought tolerant." },
  { category: "Flowers", name: "Japanese Anemone", description: "Late-season pink or white blooms, part shade." },
  { category: "Flowers", name: "Platycodon (Balloon Flower)", description: "Star-shaped blue, white, or pink blooms from balloon-like buds." },
  { category: "Flowers", name: "Clematis", description: "Climbing vine with large purple, pink, or white blooms." },
  { category: "Flowers", name: "Lily of the Nile (Agapanthus)", description: "Tall stalks topped with blue or white blooms." },
  { category: "Flowers", name: "Liriope", description: "Grass-like groundcover with violet flower spikes." },
  { category: "Flowers", name: "Poppy", description: "Oriental and Iceland varieties, bright papery blooms." },
  { category: "Flowers", name: "Garden Mum", description: "Fall-blooming, available in bronze, yellow, purple, white, red." },
  { category: "Flowers", name: "Ornamental Pepper", description: "Grown for colorful purple/red fall pods, not for eating." },
  { category: "Flowers", name: "Pansy", description: "Cool-season annual, wide range of colors, cold tolerant." },
  { category: "Flowers", name: "Viola (Johnny Jump-Up)", description: "Small-flowered cool-season annual, mixed colors." },
  { category: "Flowers", name: "Flowering Kale & Cabbage", description: "Cool-season ornamental rosettes, purple/white/pink centers." },
  { category: "Flowers", name: "Poinsettia", description: "Classic holiday plant, red, white, or pink bracts." },
  { category: "Flowers", name: "Amaryllis", description: "Large trumpet blooms, potted holiday bulb." },
  { category: "Flowers", name: "Paperwhite (Narcissus)", description: "Fragrant white clustered blooms, forced indoor bulb." },
  { category: "Flowers", name: "Hydrangea", description: "Large mophead or panicle blooms in blue, pink, or white; needs shade in Texas heat." },
  { category: "Flowers", name: "Rose", description: "Knock Out, Drift, and hybrid tea varieties, wide color range." },
  { category: "Flowers", name: "Azalea", description: "Spring-blooming shrub, pink/red/white/purple; part shade." },
  { category: "Flowers", name: "Rhododendron", description: "Large spring blooms, prefers acidic soil and part shade." },
  { category: "Flowers", name: "Butterfly Bush (Buddleja)", description: "Long purple/pink/white blooms, attracts butterflies." },
  { category: "Flowers", name: "Lilac", description: "Fragrant purple spring clusters, needs cold winters." },
  { category: "Flowers", name: "Weigela", description: "Arching shrub with pink/red trumpet blooms in spring." },
  { category: "Flowers", name: "Spirea", description: "Dense clusters of white or pink blooms, spring/summer." },
  { category: "Flowers", name: "Rose of Sharon (Althea)", description: "Hardy hibiscus shrub, purple/pink/white summer blooms." },
  { category: "Flowers", name: "Gardenia", description: "Fragrant white blooms, glossy evergreen foliage." },
  { category: "Flowers", name: "Camellia", description: "Fall or spring blooming evergreen shrub, pink/red/white." },
  { category: "Flowers", name: "Viburnum", description: "White snowball-like clusters, spring bloomer." },
  { category: "Flowers", name: "Forsythia", description: "Bright yellow branches, one of the earliest spring bloomers." },
  { category: "Flowers", name: "Mock Orange (Philadelphus)", description: "Fragrant white spring blooms." },
  { category: "Flowers", name: "Potentilla (Bush Cinquefoil)", description: "Small yellow, orange, or pink blooms all summer." },
  { category: "Flowers", name: "Honeysuckle Vine", description: "Fragrant tubular blooms, attracts hummingbirds." },
  { category: "Flowers", name: "Escallonia", description: "Evergreen privacy shrub with pink blooms." },
  { category: "Flowers", name: "Hibiscus", description: "Large tropical blooms, red/pink/yellow/white; braided tree or bush form." },
  { category: "Flowers", name: "Mandevilla Vine", description: "Climbing trellis vine, pink or red trumpet blooms." },
  { category: "Flowers", name: "Dipladenia", description: "Mounding bush relative of mandevilla, compact tropical blooms." },
  { category: "Flowers", name: "Bougainvillea", description: "Vibrant pink/purple papery bracts, climbing habit." },
  { category: "Flowers", name: "Canna Lily", description: "Large tropical leaves with hot pink/orange/red blooms." },
  { category: "Flowers", name: "Calla Lily", description: "Elegant trumpet-shaped blooms, potted accent color." },
  { category: "Flowers", name: "Bird of Paradise", description: "Orange and blue crane-shaped tropical blooms." },
  { category: "Flowers", name: "Plumeria", description: "Fragrant tropical blooms, classic Hawaiian lei flower." },
  { category: "Flowers", name: "Passion Flower", description: "Intricate purple tropical vine blooms." },
  { category: "Flowers", name: "Ixora", description: "Clustered red, orange, or yellow tropical blooms." },
  { category: "Flowers", name: "Thunbergia (Black-Eyed Susan Vine)", description: "Climbing vine, orange blooms with dark centers." },
  { category: "Flowers", name: "Orchid", description: "Phalaenopsis and Dendrobium varieties, indoor potted blooms." },
  { category: "Flowers", name: "Anthurium (Flamingo Flower)", description: "Waxy heart-shaped blooms in pink, red, or white." },
  { category: "Flowers", name: "Peace Lily", description: "White hooded blooms, shade-loving indoor plant." },
  { category: "Flowers", name: "Bromeliad", description: "Bold rosette foliage with bright neon flower spikes." },
  { category: "Flowers", name: "Kalanchoe", description: "Clustered blooms on a compact indoor succulent." },
  { category: "Flowers", name: "African Violet", description: "Fuzzy-leafed miniature indoor bloomer, purple/pink/white." },
  { category: "Flowers", name: "Tulip", description: "Classic spring bulb, wide range of colors." },
  { category: "Flowers", name: "Daffodil", description: "Yellow or white trumpet spring bulb." },
  { category: "Flowers", name: "Hyacinth", description: "Fragrant clustered spring bulb blooms." },
  { category: "Flowers", name: "Allium", description: "Globe-shaped purple bloom on a tall stem." },
  { category: "Flowers", name: "Crocus", description: "Early spring bulb, one of the first blooms of the year." },
  { category: "Flowers", name: "Dahlia", description: "Bold, full blooms from dinnerplate to compact sizes." },
  { category: "Flowers", name: "Gladiolus", description: "Tall spike of ruffled summer blooms." },
  { category: "Flowers", name: "Lily", description: "Asiatic, Oriental, and Easter varieties, large fragrant blooms." },
  { category: "Flowers", name: "Caladium", description: "Heart-shaped leaves in pink/white/green patterns, shade plant." },

  // Iconic Texas wildflowers -- an obvious miss for an Austin business,
  // added after being called out directly.
  { category: "Flowers", name: "Texas Bluebonnet", description: "The Texas state flower -- deep blue spring blooms, native wildflower." },
  { category: "Flowers", name: "Indian Paintbrush", description: "Bright red-orange spring wildflower, often grows alongside bluebonnets." },
  { category: "Flowers", name: "Indian Blanket (Firewheel)", description: "Red-and-yellow daisy-like Texas wildflower, blooms spring through summer." },
  { category: "Flowers", name: "Mexican Hat", description: "Yellow and red drooping cone-shaped wildflower, native Texas prairie plant." },

  // Additional trees requested by the owner from a broader national
  // nursery inventory list, added in full per explicit request. Named
  // cultivars/colors within a species are folded into the description
  // rather than given their own row, same treatment as the flower colors
  // above -- avoids ~5x duplication for e.g. "Crape Myrtle" in five colors.
  { category: "Trees", name: "Dogwood", description: "Spring-blooming ornamental, pink or white; Cherokee Chief, Cherokee Brave, Kousa varieties." },
  { category: "Trees", name: "Magnolia", description: "Large fragrant white blooms, glossy evergreen leaves; Little Gem, Southern, Sweetbay varieties." },
  { category: "Trees", name: "Eastern Redbud", description: "Pink/purple spring blooms; Forest Pansy, Oklahoma, Rising Sun, Ruby Falls Weeping varieties." },
  { category: "Trees", name: "Ornamental Cherry", description: "Spring flowering, non-fruiting; Kwanzan, Yoshino, Weeping Yoshino, Autumnalis varieties." },
  { category: "Trees", name: "Japanese Maple", description: "Ornamental red or coral foliage; Bloodgood, Emperor, Crimson Queen Weeping, Coral Bark varieties." },
  { category: "Trees", name: "Flowering Pear", description: "White spring blooms; Cleveland Select, Chanticleer -- note: invasive in some areas." },
  { category: "Trees", name: "Flowering Plum", description: "Purple foliage, pink spring blooms; Purple Leaf Newport, Thundercloud." },
  { category: "Trees", name: "Ornamental Crabapple", description: "Spring blooms and small decorative fruit; Prairifire, Robinson, Profusion." },
  { category: "Trees", name: "Fringe Tree", description: "White fringe-like spring blooms, native ornamental." },
  { category: "Trees", name: "Golden Rain Tree", description: "Yellow summer blooms, papery seed pods." },
  { category: "Trees", name: "Mimosa (Silk Tree)", description: "Feathery pink puff blooms, fast growing." },
  { category: "Trees", name: "Apple Tree", description: "Honeycrisp, Gala, Fuji, Granny Smith, and other common varieties." },
  { category: "Trees", name: "Peach Tree", description: "Elberta, Redhaven, Belle of Georgia, dwarf Bonanza varieties." },
  { category: "Trees", name: "Pear Tree (Fruiting)", description: "Bartlett, Kieffer, Orient, Ayers varieties." },
  { category: "Trees", name: "Asian Pear Tree", description: "Shinseiki, Hosui, 20th Century varieties." },
  { category: "Trees", name: "Plum Tree (Fruiting)", description: "Santa Rosa, Methley, Burbank, Stanley Prune varieties." },
  { category: "Trees", name: "Cherry Tree (Fruiting)", description: "Bing, Black Tartarian, Rainier, Montmorency Sour varieties." },
  { category: "Trees", name: "Fig Tree", description: "Brown Turkey, Celeste, Chicago Hardy, Black Mission varieties." },
  { category: "Trees", name: "Pomegranate Tree", description: "Wonderful and Russian 26 varieties, drought tolerant." },
  { category: "Trees", name: "Olive Tree", description: "Arbequina, Mission, dwarf Little Ollie varieties." },
  { category: "Trees", name: "Pecan Tree", description: "Stewart, Desirable, Cape Fear, Choctaw varieties -- classic Texas shade/nut tree." },
  { category: "Trees", name: "Walnut Tree", description: "Black Walnut and English Walnut varieties." },
  { category: "Trees", name: "Persimmon Tree", description: "Fuyu (non-astringent) and Hachiya varieties." },
  { category: "Trees", name: "Mulberry Tree", description: "Pakistan fruiting and weeping fruitless varieties." },
  { category: "Trees", name: "Pawpaw Tree", description: "Native fruit tree, tropical-tasting fruit." },
  { category: "Trees", name: "Lemon Tree", description: "Meyer Improved Dwarf, Eureka, Lisbon varieties." },
  { category: "Trees", name: "Lime Tree", description: "Key Lime, Persian Lime, Kaffir/Makrut varieties." },
  { category: "Trees", name: "Orange Tree", description: "Washington Navel, Valencia, Blood Orange varieties." },
  { category: "Trees", name: "Grapefruit Tree", description: "Ruby Red and seedless Marsh varieties." },
  { category: "Trees", name: "Tangerine & Mandarin Tree", description: "Clementine and Satsuma varieties." },
  { category: "Trees", name: "Kumquat Tree", description: "Nagami and Meiwa varieties." },
  { category: "Trees", name: "Shade Maple", description: "Autumn Blaze, Red Sunset, Sugar Maple, Silver Maple, Crimson King varieties." },
  { category: "Trees", name: "Oak (Shade)", description: "Shumard, Pin, White, Willow, and Bur Oak varieties." },
  { category: "Trees", name: "Weeping Willow", description: "Classic drooping-branch shade tree; Corkscrew Willow variant available." },
  { category: "Trees", name: "River Birch", description: "Peeling bark ornamental shade tree; Dura Heat, Heritage, Whitespire varieties." },
  { category: "Trees", name: "Elm (Shade)", description: "American, Frontier, and Lacebark Elm varieties." },
  { category: "Trees", name: "Autumn Purple Ash", description: "Fast-growing shade tree with purple fall color." },
  { category: "Trees", name: "Ginkgo Biloba", description: "Fan-shaped leaves, brilliant yellow fall color; fruitless male varieties available." },
  { category: "Trees", name: "Poplar & Aspen", description: "Lombardy Poplar, Quaking Aspen, Tulip Poplar varieties." },
  { category: "Trees", name: "American Sycamore", description: "Large shade tree with distinctive mottled bark; Bloodgood London Planetree variety." },
  { category: "Trees", name: "Sweetgum", description: "Star-shaped leaves, fall color; fruitless Rotundiloba variety available." },
  { category: "Trees", name: "Honey Locust", description: "Fast-growing shade tree, filtered canopy; Sunburst, Shademaster varieties." },
  { category: "Trees", name: "Dawn Redwood", description: "Fast-growing deciduous conifer, feathery foliage." },
  { category: "Trees", name: "Catalpa", description: "Large heart-shaped leaves, showy white spring blooms." },
  { category: "Trees", name: "Hornbeam", description: "Dense, slow-growing shade tree; American and European Fastigiate varieties." },
  { category: "Trees", name: "Arborvitae", description: "Evergreen privacy screening; Green Giant (fast), Emerald Green, Little Giant Dwarf varieties." },
  { category: "Trees", name: "Cypress (Privacy)", description: "Leyland Cypress and columnar Italian Cypress for screening." },
  { category: "Trees", name: "Pine", description: "Loblolly, Eastern White, Mugo Dwarf, Slash, and Austrian Pine varieties." },
  { category: "Trees", name: "Spruce", description: "Colorado Blue, Norway, Alberta Dwarf, and White Spruce varieties." },
  { category: "Trees", name: "Juniper", description: "Skyrocket Blue, Spartan, Blue Point, Hollywood, Wichita Blue varieties." },
  { category: "Trees", name: "Cedar", description: "Deodara, Lebanon, Eastern Red, and Western Red Cedar varieties." },
  { category: "Trees", name: "Yew", description: "Columnar evergreen, Hicks Yew variety common for hedging." },
  { category: "Trees", name: "Hemlock", description: "Canadian Hemlock, dense evergreen shade/privacy tree." },
  { category: "Trees", name: "Holly Tree", description: "Evergreen with red berries; Nellie R. Stevens, Foster, American Holly varieties." },
  { category: "Trees", name: "Palm", description: "Windmill (cold-hardy), Pygmy Date, Majesty, Sago, Queen, and Washingtonia varieties." },
  { category: "Trees", name: "Banana Tree", description: "Musa Basjoo (cold-hardy) and dwarf Cavendish varieties." },
  { category: "Trees", name: "Ficus Tree", description: "Fiddle Leaf Fig, Weeping Fig, and Rubber Tree varieties, indoor/patio." },
  { category: "Trees", name: "Jacaranda", description: "Fern-like foliage with vivid purple spring blooms." },
  { category: "Trees", name: "Royal Poinciana", description: "Flamboyant orange-red summer canopy bloom." },

  // Bushes & Hedges -- Austin/Central Texas appropriate privacy and
  // ornamental shrubs.
  { category: "Bushes & Hedges", name: "Boxwood", description: "Classic formal hedge, dense compact evergreen, slow growing." },
  { category: "Bushes & Hedges", name: "Cherry Laurel", description: "Cold-hardy evergreen privacy hedge, glossy leaves." },
  { category: "Bushes & Hedges", name: "Hicks Yew", description: "Columnar evergreen, cold-hardy formal hedge option." },
  { category: "Bushes & Hedges", name: "Wax Myrtle", description: "Fast-growing aromatic evergreen screen, Austin-area favorite." },
  { category: "Bushes & Hedges", name: "Photinia", description: "Vibrant red new growth, dense evergreen privacy hedge." },
  { category: "Bushes & Hedges", name: "Ligustrum (Privet)", description: "Fast-growing dense screening hedge, classic shaped-hedge choice." },
  { category: "Bushes & Hedges", name: "Nandina (Heavenly Bamboo)", description: "Evergreen with red winter berries and fall foliage color." },
  { category: "Bushes & Hedges", name: "Burford Holly", description: "Dense evergreen with bright red berries, good privacy screen." },
  { category: "Bushes & Hedges", name: "Dwarf Yaupon Holly", description: "Compact evergreen, low-maintenance formal hedge or border." },
  { category: "Bushes & Hedges", name: "Indian Hawthorn", description: "Compact evergreen shrub with spring blooms, good border hedge." },
  { category: "Bushes & Hedges", name: "Abelia", description: "Arching evergreen shrub with small fragrant blooms, informal hedge." },
  { category: "Bushes & Hedges", name: "Barberry", description: "Colorful foliage shrub, thorny, works as a barrier hedge." },
  { category: "Bushes & Hedges", name: "Loropetalum (Chinese Fringe Flower)", description: "Burgundy foliage with pink fringe blooms, evergreen hedge." },

  // Plants -- groundcovers, ornamental grasses, ferns, and succulents,
  // Austin/Central Texas appropriate.
  { category: "Plants", name: "Big Muhly", description: "Ornamental grass, blue-gray foliage with silvery fall seed heads, 4-5ft." },
  { category: "Plants", name: "Mexican Feather Grass", description: "Fine lime-green blades turning soft blonde in summer, drought tolerant." },
  { category: "Plants", name: "Gulf Muhly", description: "Native ornamental grass, pink-purple plumes in fall." },
  { category: "Plants", name: "Bamboo Muhly", description: "Airy, bamboo-like ornamental grass, good privacy screen or accent." },
  { category: "Plants", name: "Southern Maidenhair Fern", description: "Delicate semi-evergreen fern for shaded areas." },
  { category: "Plants", name: "Foxtail Fern", description: "Bushy plume-like fronds, part to full shade, handles Texas heat." },
  { category: "Plants", name: "Frogfruit", description: "Native groundcover with small white blooms, tolerates foot traffic." },
  { category: "Plants", name: "Silver Ponyfoot", description: "Trailing silver-leaved groundcover, very drought tolerant." },
  { category: "Plants", name: "Asian Jasmine", description: "Dense evergreen groundcover, popular low-maintenance lawn alternative." },
  { category: "Plants", name: "Purple Heart", description: "Purple trailing foliage groundcover, heat and drought tolerant." },
  { category: "Plants", name: "Agave", description: "Bold architectural succulent, very drought tolerant, various sizes." },
  { category: "Plants", name: "Yucca", description: "Spiky architectural evergreen, extremely drought tolerant." },
  { category: "Plants", name: "Artemisia", description: "Silvery aromatic foliage plant, drought tolerant accent/border." },
  { category: "Plants", name: "Aloe Vera", description: "Low-growing succulent, spiky fleshy leaves, very low maintenance." },
];

async function main() {
  let created = 0;
  for (const item of ITEMS) {
    await prisma.materialCatalogItem.upsert({
      where: { category_name: { category: item.category, name: item.name } },
      update: { description: item.description },
      create: item,
    });
    created++;
  }
  console.log(`Seeded ${created} material catalog items.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
